/**
 * Mock Provider
 * =============
 * Fake LLM provider for testing without API calls.
 *
 * Features:
 * - Generates deterministic "embeddings" (for testing similarity)
 * - Returns canned responses for completions
 * - Simulates realistic token counts
 * - No external dependencies
 *
 * Use cases:
 * - Development without API keys
 * - Unit testing
 * - CI/CD pipelines
 */

import type { LlmProvider, CompletionParams } from './llmProvider.interface.js';
import type { EmbeddingResult, CompletionResult } from '../../types/index.js';
import { getConfig } from '../../config/index.js';
import { logger } from '../../utils/logger.js';

// ===========================================
// Mock Provider Implementation
// ===========================================

export class MockProvider implements LlmProvider {
  readonly name = 'mock';
  private embeddingDimensions: number;

  constructor() {
    const config = getConfig();
    this.embeddingDimensions = config.embeddingDimensions;
  }

  isConfigured(): boolean {
    return true; // Always configured
  }

  // ===========================================
  // Embeddings
  // ===========================================

  async embed(text: string): Promise<EmbeddingResult> {
    // Generate a deterministic "embedding" based on text hash
    // This allows testing similarity search with consistent results
    const embedding = this.generateMockEmbedding(text);
    const tokenCount = Math.ceil(text.length / 4);

    logger.debug({
      provider: 'mock',
      inputLength: text.length,
      tokenCount,
    }, 'Mock embedding generated');

    return {
      embedding,
      tokenCount,
    };
  }

  async embedBatch(texts: string[]): Promise<EmbeddingResult[]> {
    return Promise.all(texts.map((text) => this.embed(text)));
  }

  // ===========================================
  // Completions
  // ===========================================

  async complete(params: CompletionParams): Promise<CompletionResult> {
    // Generate a mock response based on the prompt
    const content = this.generateMockResponse(params);
    const inputTokens = Math.ceil((params.systemPrompt.length + params.userPrompt.length) / 4);
    const outputTokens = Math.ceil(content.length / 4);

    logger.debug({
      provider: 'mock',
      inputTokens,
      outputTokens,
    }, 'Mock completion generated');

    // Simulate some latency
    await new Promise((resolve) => setTimeout(resolve, 100));

    return {
      content,
      inputTokens,
      outputTokens,
      model: 'mock',
    };
  }

  // ===========================================
  // Mock Generation Logic
  // ===========================================

  /**
   * Generate a deterministic embedding from text
   * Uses simple hash to create reproducible vectors
   */
  private generateMockEmbedding(text: string): number[] {
    const embedding = new Array(this.embeddingDimensions).fill(0);

    // Create a simple hash-based embedding
    // Similar texts will have somewhat similar embeddings
    for (let i = 0; i < text.length; i++) {
      const charCode = text.charCodeAt(i);
      const index = (charCode * (i + 1)) % this.embeddingDimensions;
      embedding[index] = (embedding[index] ?? 0) + (charCode / 255 - 0.5);
    }

    // Normalize the vector
    const magnitude = Math.sqrt(
      embedding.reduce((sum, val) => sum + val * val, 0)
    );

    if (magnitude > 0) {
      for (let i = 0; i < embedding.length; i++) {
        embedding[i] = (embedding[i] ?? 0) / magnitude;
      }
    }

    return embedding;
  }

  /**
   * Generate a mock response based on prompt content
   */
  private generateMockResponse(params: CompletionParams): string {
    const userPrompt = params.userPrompt.toLowerCase();

    // Check if JSON mode is requested
    if (params.jsonMode) {
      return this.generateMockJsonResponse(userPrompt);
    }

    // Check for common patterns in prompts
    if (userPrompt.includes('begin_context') && userPrompt.includes('end_context')) {
      return this.generateMockRagResponse(params.userPrompt);
    }

    // Default response
    return `This is a mock response from the test LLM provider.

Based on the provided context, I can offer the following information:

1. The document contains relevant information about the query.
2. Key points have been identified and summarized.
3. Citations are available for verification.

[chunk-0] This citation references the source material.

Confidence: MEDIUM

Note: This is a mock response for testing purposes. In production, this would be generated by a real LLM.`;
  }

  /**
   * Generate mock RAG response with citations
   */
  private generateMockRagResponse(prompt: string): string {
    // Extract question from prompt
    const questionMatch = prompt.match(/User Question:\s*(.+?)(?:\n|$)/i);
    const question = questionMatch ? questionMatch[1] : 'the query';

    return `Based on the provided documents, here is my answer to "${question}":

The documents contain information relevant to your question. [chunk-0] The key findings suggest that the content addresses your query directly.

Additionally, [chunk-1] there are supporting details that provide context for this answer.

Confidence: MEDIUM

This answer is based solely on the provided document context. If you need more specific information, please provide additional documents or clarify your question.`;
  }

  /**
   * Generate mock JSON response for extraction
   */
  private generateMockJsonResponse(prompt: string): string {
    // Try to detect what kind of extraction is requested
    if (prompt.includes('invoice')) {
      return JSON.stringify({
        invoiceNumber: 'INV-MOCK-001',
        date: '2024-01-15',
        vendor: 'Mock Vendor Inc.',
        total: 1234.56,
        items: [
          { description: 'Mock Service', quantity: 1, price: 1000.00 },
          { description: 'Mock Product', quantity: 2, price: 117.28 },
        ],
        confidence: 0.85,
      }, null, 2);
    }

    if (prompt.includes('resume') || prompt.includes('cv')) {
      return JSON.stringify({
        name: 'John Mock',
        email: 'john.mock@example.com',
        phone: '+1-555-MOCK',
        experience: [
          {
            title: 'Senior Developer',
            company: 'Mock Corp',
            duration: '2020-2024',
          },
        ],
        skills: ['TypeScript', 'React', 'Node.js'],
        confidence: 0.90,
      }, null, 2);
    }

    // Generic extraction response
    return JSON.stringify({
      extracted: true,
      fields: {
        field1: 'Mock value 1',
        field2: 'Mock value 2',
        field3: 123,
      },
      confidence: 0.75,
      note: 'This is a mock extraction for testing purposes',
    }, null, 2);
  }
}
